#服务端口
server:
  port: 8002
spring:
  #服务名
  application:
    name: server_cos
  #环境设置
  profiles:
    active: dev

tencent:
  cos:
    secretId: *
    secretKey: *
    region: ap-beijing
    bucketName: edu-1312533782

