#服务端口
server:
  port: 8002
spring:
  #服务名
  application:
    name: server_cos
  #环境设置
  profiles:
    active: dev

tencent:
  cos:
    secretId: AKID71f28xUlkSt3wYsvhCQN3SZPyLQEl1zg
    secretKey: RbU7TaQz2sTotiHacOvCCvPecKn0xe5G
    region: ap-beijing
    bucketName: edu-1312533782

